.TH "m.log.bcolors" 3 "Tue Mar 18 2014" "Version 0.3" "TornadoServerMI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.log.bcolors \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBDEBUG\fP = '\\033[94m'"
.br
.ti -1c
.RI "string \fBINFO\fP = '\\033[95m'"
.br
.ti -1c
.RI "string \fBSUCCESS\fP = '\\033[92m'"
.br
.ti -1c
.RI "string \fBWARNING\fP = '\\033[93m'"
.br
.ti -1c
.RI "string \fBFAIL\fP = '\\033[91m'"
.br
.ti -1c
.RI "string \fBENDC\fP = '\\033[0m'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Define constant value color for different level

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TornadoServerMI from the source code\&.
