.TH "m.log.Log" 3 "Tue Apr 1 2014" "Version 1.0" "TornadoServerMI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.log.Log \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBprintL\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlogger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Log Manager

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def m\&.log\&.Log\&.__init__ (self)"

.PP
.nf
Define 3 differents log :
activity.log -> all activity server
warning.log -> only warning server (including illegal acess)
error.log' -> error server
Write all message on terminal too

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def m\&.log\&.Log\&.printL (self, pMsg, pLvl)"

.PP
.nf
Add color and write in log with an define level
pMsg : message to write in log
pLvl : level of log message

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TornadoServerMI from the source code\&.
