.TH "m.loadConf.LoadConf" 3 "Tue Mar 18 2014" "Version 0.3" "TornadoServerMI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.loadConf.LoadConf \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBloadValue\fP"
.br
.ti -1c
.RI "def \fBisBlind\fP"
.br
.ti -1c
.RI "def \fBipCamera\fP"
.br
.ti -1c
.RI "def \fBportCamera\fP"
.br
.ti -1c
.RI "def \fBipServ\fP"
.br
.ti -1c
.RI "def \fBportServ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Loading configuration file
.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def m\&.loadConf\&.LoadConf\&.isBlind (self)"

.PP
.nf
Return true if configuration is for Blind
Else false

.fi
.PP
 
.SS "def m\&.loadConf\&.LoadConf\&.loadValue (self, key)"

.PP
.nf
Return the value associate to the key into conf file (fichier/conf)
Else return "error"

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TornadoServerMI from the source code\&.
