.TH "m.log.SingleLevelFilter" 3 "Thu Apr 3 2014" "Version 1.0" "MI Protect Privacy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.log.SingleLevelFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Filter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBfilter\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpasslevel\fP"
.br
.ti -1c
.RI "\fBreject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Filter for one level
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def m\&.log\&.SingleLevelFilter\&.__init__ (self, passlevel, reject)"

.PP
.nf
Constructor
passlevel : level to filter
reject : true on reject state

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for MI Protect Privacy from the source code\&.
