.TH "m.log.lvl" 3 "Thu Apr 3 2014" "Version 1.0" "MI Protect Privacy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.log.lvl \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNOTSET\fP = 0"
.br
.ti -1c
.RI "int \fBDEBUG\fP = 10"
.br
.ti -1c
.RI "int \fBINFO\fP = 20"
.br
.ti -1c
.RI "int \fBSUCCESS\fP = 25"
.br
.ti -1c
.RI "int \fBWARNING\fP = 30"
.br
.ti -1c
.RI "int \fBFAIL\fP = 40"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Define constant value for level log

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for MI Protect Privacy from the source code\&.
