.TH "m.loadConf.ConfigError" 3 "Tue Mar 18 2014" "Version 0.3" "TornadoServerMI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
m.loadConf.ConfigError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fB__str__\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Exception : error loading configuration
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TornadoServerMI from the source code\&.
