.TH "superTornado.GlobalVars" 3 "Tue Apr 1 2014" "Version 1.0" "TornadoServerMI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
superTornado.GlobalVars \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBconfig\fP = \fBLoadConf\fP('m/fichier/conf')"
.br
.ti -1c
.RI "tuple \fBlog\fP = \fBLog\fP()"
.br
.ti -1c
.RI "\fBblind\fP = False"
.br
.ti -1c
.RI "string \fBipCamera\fP = ''"
.br
.ti -1c
.RI "string \fBportCamera\fP = ''"
.br
.ti -1c
.RI "string \fBendUrlCamera\fP = ''"
.br
.ti -1c
.RI "string \fBidCamera\fP = ''"
.br
.ti -1c
.RI "string \fBurlCamera\fP = ''"
.br
.ti -1c
.RI "string \fBportServ\fP = ''"
.br
.ti -1c
.RI "string \fBurlSocket\fP = ''"
.br
.ti -1c
.RI "string \fBipDomo\fP = ''"
.br
.ti -1c
.RI "string \fBportDomo\fP = ''"
.br
.ti -1c
.RI "int \fBauthorized\fP = 0"
.br
.ti -1c
.RI "int \fBunauthorized\fP = 0"
.br
.ti -1c
.RI "tuple \fBloop\fP = tornado\&.ioloop\&.IOLoop\&.instance()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Global vars for server

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TornadoServerMI from the source code\&.
