.TH "superTornado.BaseHandler" 3 "Tue Mar 18 2014" "Version 0.3" "TornadoServerMI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
superTornado.BaseHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RequestHandler\&.
.PP
Inherited by \fBsuperTornado\&.DisconnectionHandler\fP, \fBsuperTornado\&.MainHandler\fP, \fBsuperTornado\&.UnauthorizedHandler\fP, \fBsuperTornado\&.VideoHandler\fP, and \fBsuperTornado\&.WSocketHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_current_user\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Define BaseHandler for create the basis for session connection
cookie secure  based (sign and timestamp )

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for TornadoServerMI from the source code\&.
