.TH "superTornado.UnauthorizedHandler" 3 "Thu Apr 3 2014" "Version 1.0" "MI Protect Privacy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
superTornado.UnauthorizedHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBsuperTornado\&.BaseHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget\fP"
.br
.ti -1c
.RI "def \fBpost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Unauthorized web page : /unauthorized in http server

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def superTornado\&.UnauthorizedHandler\&.get (self)"

.PP
.nf
GET request -> show the illegal.html page

.fi
.PP
 
.SS "def superTornado\&.UnauthorizedHandler\&.post (self)"

.PP
.nf
POST request ->
if parameter POST force == 1
    force acess to camera
else
     go to / page (MainHandler)

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for MI Protect Privacy from the source code\&.
